apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-docker-learning
  labels:
    app: kubernetes-docker-learning
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetes-docker-learning
  template:
    metadata:
      labels:
        app: kubernetes-docker-learning
    spec:
      containers:
        - name: kubernetes-docker-learning
          image: spring-docker-image-new.jar:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: department-service-svc
spec:
  type : LoadBalancer
  ports:
    - targetPort: 8080
      port: 80
  selector:
    app: kubernetes-docker-learning